<a href="https://colab.research.google.com/github/Claudio-Ferriz/Proyecto-Ciencia-de-Datos-para-Politologos/blob/main/Encuesta_de_Materias_CP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerías de Python

In [2]:
# Importación y ejecución de las librerías de Python para el análisis y modelado
# de datos.

!pip install faker

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from faker import Faker
import random

Collecting faker
  Downloading faker-40.15.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.15.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 12.6 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.15.0

# Dataframes

## Dataframe Encuestas de Materias

In [3]:
# Generación de datos ficticios

# Inicio de Faker (para uso en español)

fake = Faker('es_ES')

n_registros = 1560

# Lista de materias obligatorias

materias_list = [
    "Fundamentos de Ciencia Política I", "Teoría Política y Social I", "Economía",
    "Fundamentos de Ciencia Política II", "Teoría Política y Social II", "Historia Contemporánea",
    "Filosofía y Métodos de las Ciencias Sociales", "Historia", "Latinoamericana",
    "Política Latinoamericana", "Teoría Sociológica", "Metodología de la Investigación en Ciencia Política I",
    "Metodología de la Investigación en Ciencia Política II", "Teoría Política Contemporánea",
    "Historia Argentina", "Política Argentina", "Teoría y Derecho Constitucional",
    "Sociología Política", "Filosofía", "Teoría de las Relaciones Internacionales",
    "Opinión Pública", "Sistemas Políticos Comparados", "Administración y Políticas Públicas"
]


# Columna de dictado

dictado_opciones = ["presencial", "hibrido", "virtual"]

# Generación de datos con Faker

data = []

for i in range(n_registros):
    registro = {

        'encuesta': f"ENC-{str(i+1).zfill(4)}",

        'fecha de encuesta': fake.date_time_between(start_date='-500d', end_date='now'),

        'materia': fake.random_element(elements=materias_list),
        'catedra': None,

        'comisión': fake.random_int(min=1, max=8),
        'dictado de la materia': fake.random_element(elements=dictado_opciones),
        'evaluación': fake.random_int(min=1, max=10),
        'opiniones generales de la materia': None
    }
    data.append(registro)

# Creación del DataFrame Encuestas

df_encuestas = pd.DataFrame(data)

In [4]:
df_encuestas

,encuesta,fecha de encuesta,materia,catedra,comisión,dictado de la materia,evaluación,opiniones generales de la materia
0,ENC-0001,2025-04-07 07:02:56.459516,Teoría Sociológica,None,6,hibrido,7,None
1,ENC-0002,2025-07-19 03:06:28.275179,Metodología de la Investigación en Ciencia Pol...,None,5,virtual,4,None
2,ENC-0003,2025-01-08 10:46:54.974063,Sistemas Políticos Comparados,None,4,presencial,6,None
3,ENC-0004,2025-07-27 00:42:50.178159,Fundamentos de Ciencia Política I,None,3,hibrido,1,None
4,ENC-0005,2025-10-10 01:06:07.080286,Sociología Política,None,7,hibrido,5,None
...,...,...,...,...,...,...,...,...
1555,ENC-1556,2025-04-23 11:22:57.208621,Filosofía,None,3,hibrido,3,None
1556,ENC-1557,2025-08-18 22:54:25.510005,Teoría Sociológica,None,7,hibrido,1,None
1557,ENC-1558,2025-03-04 01:23:34.934065,Fundamentos de Ciencia Política I,None,7,presencial,9,None
1558,ENC-1559,2025-04-24 00:55:04.206366,Política Latinoamericana,None,5,virtual,9,None
1559,ENC-1560,2025-02-16 10:05:58.216774,Filosofía y Métodos de las Ciencias Sociales,None,2,presencial,9,None

In [5]:
# Analisis de la cantidad de registros, datos no nulos y tipo de datos del
# dataframe Encuestas de Materias

df_encuestas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   encuesta                           1560 non-null   object
 1   fecha de encuesta                  1560 non-null   datetime64[ns]
 2   materia                            1560 non-null   object
 3   catedra                            0 non-null      object
 4   comisión                           1560 non-null   int64
 5   dictado de la materia              1560 non-null   object
 6   evaluación                         1560 non-null   int64
 7   opiniones generales de la materia  0 non-null      object
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 97.6+ KB

## Dataframe Estudiantes de Ciencia Política

In [6]:
# Importación del dataset Estudiantes de Ciencia Política y generación del
# dataframe Estudiantes

df_estudiantes = pd.read_csv('https://github.com/Claudio-Ferriz/Proyecto-Ciencia-de-Datos-para-Politologos/raw/refs/heads/main/dataset_estudiantes1.csv',
    delimiter=';',
    header=0,
    names=None,
    index_col=0,
    usecols=None,
    dtype=None,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    quotechar='"',
    encoding='latin-1')

In [7]:
df_estudiantes

          nro_documento        apellido           nombres carrera
N° Orden
1              45925917           ABACA      JUAN SEGUNDO      CP
2              44655426            ABAD         ANTONELLA      CP
3              32436697           ABATE       JUAN MANUEL      CP
4              43871005           ABDUL   SANTIAGO ANDRES      CP
5              43744973         ACEVEDO    MERCEDES MARÍA      CP
...                 ...             ...               ...     ...
2560           42583296  ZIGARAN GASPAR  ARIADNA GABRIELA      CP
2561           43012938     ZOLOTARCHUK       LEONEL IVÁN      CP
2562           45331679         ZOTTOLA      KAREN NICOLE      CP
2563           46360303       ZUMARRAGA         GUADALUPE      CP
2564           40936492          ZUNINO      MARIANO JUAN      CP

[2564 rows x 4 columns]

In [8]:
# Analisis de la cantidad de registros, datos no nulos y tipo de datos del
# dataframe Estudiantes

df_estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2564 entries, 1 to 2564
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nro_documento  2564 non-null   int64
 1   apellido       2564 non-null   object
 2   nombres        2564 non-null   object
 3   carrera        2564 non-null   object
dtypes: int64(1), object(3)
memory usage: 100.2+ KB

# Guardado de Dataframes

In [ ]:
# Guardado en formato Excel del dataframe Encuestas de Materias

df_encuestas.to_excel('dataset_encuestas_materias_ciencia_política.xlsx', index=False)

In [ ]:
# Guardado en formato Excel del dataframe Estudiantes

df_estudiantes.to_excel('dataset_estudiantes_ciencia_política.xlsx', index=False)